services:
  inventorymanagement_api:
    image: inventorymanagementapi
    build:
      context: .
      dockerfile: InventoryManagement.Api/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - sqlite-data:/InventoryManagement.Api/Sqlite

volumes:
  sqlite-data:
